# -*- coding: utf-8 -*-
"""ToolsinLangchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9UV09E59C-_OJ-Dqzqu1wzEE24V-ddu

Built in tools in langchain
"""

from langchain_community.tools import DuckDuckGoSearchRun

pip install -U ddgs

search_tool= DuckDuckGoSearchRun()

results= search_tool.invoke('cricket news')

print(results)

"""Built in Tool - Shell Tool"""

from langchain_community.tools import ShellTool

shell_tool= ShellTool()

results= shell_tool.invoke('whoami')

print(results)

"""Custom Tools in Langchain

"""

from langchain_core.tools import tool

def multiply(a,b):
  """Multiply two numbers"""
  return a*b

# now add tool decorator

@tool
def multiply(a:int,b:int)->int:
  """Multiply two numbers"""
  return a*b

result= multiply.invoke({'a':2,'b':3})

print(result)

print(multiply)



"""Method 2 => Using StructuredTool

"""

from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

class MultiplyInput(BaseModel):
  a: int = Field(required= True, description='the first number to use')
  b: int = Field(required= True, description='the second number to use')

def multiply_func(a:int,b:int)->int:
  """Multiply two numbers"""
  return a*b

multiply_tool= StructuredTool.from_function(
    func= multiply_func,
    name='multiply',
    description='Multiply two numbers',
    input_type=MultiplyInput
)

result= multiply.invoke({'a':3, 'b':33})

print(result)

"""Method 3 - Using BaseTool Class"""

from langchain_core.tools import BaseTool
from typing import Type

class MultiplyInput(BaseModel):
  a: int = Field(required= True, description='the first number to use')
  b: int = Field(required= True, description='the second number to use')

class MultiplyTool(BaseTool):

  name: str="multiply"
  description:str= "Multiply two numbers"

  args_schema: Type[BaseModel]= MultiplyInput

  def _run(self, a:int , b:int)-> int:
    return a*b

multiply_tool= MultiplyTool()

multiply_tool.invoke({'a':10,'b':23})

# import os
# os.environ["HUGGINGFACEHUB_API_TOKEN"]="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"

"""Tool Calling in Langchain



"""

pip install langchain_google_genai faiss-cpu tiktoken python-dotenv langchain_text_splitters

from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.messages import HumanMessage
import requests

pip install langchain-huggingface



#tool create

@tool
def multiply(a:int, b:int):
  """Given two numbers a and b, this tool returns their product"""
  return a*b

print(multiply.invoke({'a':3, 'b':55}))

# from dotenv import load_dotenv
# load_dotenv()

# import os



# llm = ChatGoogleGenerativeAI(
#     model="gemini-3.8-flash",
#     api_key="
#     temperature=0.3
# )

llm= HuggingFaceEndpoint(
    repo_id="meta-llama/Llama-3.1-8B-Instruct",


)

model= ChatHuggingFace(llm=llm)

model.invoke('Hi how are you')

#binding our tool with LLM

# llm_with_tools= llm.bind_tools([multiply])

#with huggingface

llm_with_tools= model.bind_tools([multiply])

query= HumanMessage('can you multiply 3 with 44')



messages= [query]

result= llm_with_tools.invoke(messages)
## result is goiong to be a tool call with the tool suggested by LLM

print(result.tool_calls[0])

tool_result= multiply.invoke(result.tool_calls[0])

print(tool_result)

messages.append(tool_result)

print(messages)

final_result= llm_with_tools.invoke(messages)

print(final_result)

"""Currency conversion tool

"""

#tool create

@tool
def get_conversion_factor(base_currency:str, target_currency:str)-> float:
  """
  This function fetches the currency factor between the base currency and the target currency
  """
  url= f"https://v6.exchangerate-api.com/v6/f1f61695740f24098155eea7/pair/{base_currency}/{target_currency}"

  response= requests.get(url)
  response_json= response.json()
  return response_json['conversion_rate']

get_conversion_factor.invoke({'base_currency':'USD', 'target_currency':'INR'})

from langchain_core.tools import InjectedToolArg
from typing import Annotated

@tool
def convert(base_currency_value: int, conversion_rate:Annotated[float, InjectedToolArg])->float:
    """
    Given a currency conversion rate this tool converts the base currency into the target currency
    """
    return base_currency_value*conversion_rate

convert.invoke({'base_currency_value':100,'conversion_rate':86.56})

#tool binding

llm_with_tools= model.bind_tools([get_conversion_factor, convert])

messages= [HumanMessage("what is the conversion factor between USD and INR, and based on that can you convert 96 usd to inr")]

ai_message= llm_with_tools.invoke(messages)

print(ai_message)

ai_message.tool_calls

for tool_call in ai_message.tool_calls:
    #execute the 1st tool and get the value of the conversion rate
    if tool_call['name']=='get_conversion_factor':
       tool_message1= get_conversion_factor.invoke(tool_call)
       #fetch the conversion rate
       conversion_rate= tool_message1.content
       messages.append(tool_message1)

    #execute the 2nd tool using the conversion rate from tool 1

    if tool_call['name']=='convert':
       #fetch the current arguments
       tool_call['args']['conversion_rate']= conversion_rate
       tool_message2= convert.invoke(tool_call)
       messages.append(tool_message2)

messages

llm_with_tools.invoke(messages)