# -*- coding: utf-8 -*-
"""ToolsinLangchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9UV09E59C-_OJ-Dqzqu1wzEE24V-ddu

Built in tools in langchain
"""

from langchain_community.tools import DuckDuckGoSearchRun

pip install -U ddgs

search_tool= DuckDuckGoSearchRun()

results= search_tool.invoke('cricket news')

print(results)

"""Built in Tool - Shell Tool"""

from langchain_community.tools import ShellTool

shell_tool= ShellTool()

results= shell_tool.invoke('whoami')

print(results)

"""Custom Tools in Langchain

"""

from langchain_core.tools import tool

def multiply(a,b):
  """Multiply two numbers"""
  return a*b

# now add tool decorator

@tool
def multiply(a:int,b:int)->int:
  """Multiply two numbers"""
  return a*b

result= multiply.invoke({'a':2,'b':3})

print(result)

print(multiply)



"""Method 2 => Using StructuredTool

"""

from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

class MultiplyInput(BaseModel):
  a: int = Field(required= True, description='the first number to use')
  b: int = Field(required= True, description='the second number to use')

def multiply_func(a:int,b:int)->int:
  """Multiply two numbers"""
  return a*b

multiply_tool= StructuredTool.from_function(
    func= multiply_func,
    name='multiply',
    description='Multiply two numbers',
    input_type=MultiplyInput
)

result= multiply.invoke({'a':3, 'b':33})

print(result)

"""Method 3 - Using BaseTool Class"""

from langchain_core.tools import BaseTool
from typing import Type

class MultiplyInput(BaseModel):
  a: int = Field(required= True, description='the first number to use')
  b: int = Field(required= True, description='the second number to use')

class MultiplyTool(BaseTool):

  name: str="multiply"
  description:str= "Multiply two numbers"

  args_schema: Type[BaseModel]= MultiplyInput

  def _run(self, a:int , b:int)-> int:
    return a*b

multiply_tool= MultiplyTool()

multiply_tool.invoke({'a':10,'b':23})