# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxWqLImWZtsCtfMclTppuHWuvFsvX-V7
"""



!pip install -q youtube-transcript-api langchain-community langchain_google_genai \
               faiss-cpu tiktoken python-dotenv langchain_text_splitters

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""Step 1a- Indexing (document ingestion)

"""

video_id = "Gfr50f6ZBvo" # only the ID, not full URL
try:
    api= YouTubeTranscriptApi()
    # If you don’t care which language, this returns the “best” one
    transcript_list = api.fetch(video_id, languages=["en"])


    # Flatten it to plain text
    transcript = " ".join(snippet.text for snippet in transcript_list.snippets)
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

transcript[:1000]

"""step 1b Text Splitting
RecursiveCharacterTextSplitter

"""

splitter= RecursiveCharacterTextSplitter(chunk_size=1500, chunk_overlap= 100)


chunks= splitter.create_documents([transcript])

len(chunks)

chunks[0].page_content

"""Step 1c & 1d Indexing (Embedding generation and storing in vector store)

"""

embeddings= GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-2",
    task_type="RETRIEVAL_DOCUMENT",
    api_key="AQ.Ab8RN6KgGDD3xS55AlroDV7EflAS56AYXfhnPRSfpxx0-PZAog"
)
vector_store= FAISS.from_documents(chunks, embeddings)

"""Step 3 Retrriver

"""

retriever= vector_store.as_retriever(search_type='similarity', search_kwargs= {"k":4 })

retriever

retriever.invoke('what is deep mind')

"""Step 3 - Augmentation"""

llm = ChatGoogleGenerativeAI(
    model="gemini-3.8-flash",
    api_key="AQ.Ab8RN6KgGDD3xS55AlroDV7EflAS56AYXfhnPRSfpxx0-PZAog",
    temperature=0.3
)

prompt = PromptTemplate(
    template="""You are a helpful assistant.
Answer ONLY from the provided transcript context.
If the context is insufficient, just say you don't know.

{context}
Question: {question}""",
    input_variables=['context', 'question']
)

question= 'is the topic of aliens discussed in this video'
retrieved_docs= retriever.invoke(question)

context_text= "\n\n".join(doc.page_content for doc in  retrieved_docs)

context_text

final_prompt= prompt.invoke({'context': context_text, 'question': question})

final_prompt

"""step 4 Generation

"""

answer= llm.invoke(final_prompt)

print(answer.content)

"""Build a chain

"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  contetxt_text= "\n\n".join(doc.page_content for doc in retrieved_docs)

  return context_text

parallel_chain= RunnableParallel({
    'context':retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parallel_chain.invoke('who is Demis')

parser= StrOutputParser()

main_chain= parallel_chain | prompt | llm | parser

result=main_chain.invoke('Can you summarize the video')

type(result)